/*
* PROGRAMA QUE CHECA A MINHA BASE DE CADASTRO_PRODUTO
*/

LIBNAME DANIEL "/work/sistema/cib/daniel_sas";

* DETALHES DA LIB, NOME DAS BASES E TAMANHO EM MEMÓRIA ;
PROC DATASETS
	LIB=DANIEL DETAILS;
RUN;

* DETALHES DE UMA TABELA, NOME DAS COLUNAS, TAMANHO EM MEMÓRIA, ... ;
PROC CONTENTS
	DATA=DANIEL.CADASTRO_PRODUTO;
RUN;

* IMPRIMIR A TABELA ;
PROC PRINT
	DATA=DANIEL.CADASTRO_PRODUTO;
RUN;

* GERAR TRÊS RELATÓRIOS COUNT DETALHADOS COM PORCENTAGEM E ACUMULADO ;
PROC FREQ
	DATA=DANIEL.CADASTRO_PRODUTO;
	TABLE GENERO PLATAFORMA NOME;
RUN;

* QUANTIDADE DE CATEGORIAS DIFERENTES EM CADA COLUNA ;
PROC FREQ
	DATA=DANIEL.CADASTRO_PRODUTO NLEVELS;
	TABLE GENERO PLATAFORMA NOME;
RUN;

* CRIAR UMA NOVA TABELA E ACRESCENTAR UMA COLUNA ;
DATA TESTE;
SET DANIEL.CADASTRO_PRODUTO;

IF DATA > 201606 
	THEN LANCAMENTO = 'SIM';
	ELSE LANCAMENTO = 'NAO';

RUN;

* IMPRIMIR A NOVA TABELA ;
PROC PRINT
	DATA=WORK.TESTE;
RUN;

* COUNT DETALHADO DA COLUNA LANÇAMENTO ;
PROC FREQ
	DATA=WORK.TESTE;
	TABLE LANCAMENTO;
RUN;

* COUNT DETALHADO CRUZADO DAS COLUNAS ;
PROC FREQ
	DATA=WORK.TESTE;
	TABLE GENERO*LANCAMENTO
	/ NOCOL NOROW NOPERCENT /*NOFREQ*/ ;  */OPÇÕES PARA RETIRAR DETALHES*/
RUN;

* COUNT EM FORMATO DE LISTA ;
PROC FREQ
	DATA=WORK.TESTE NLEVELS;
	TABLE NOME;
	TABLE NOME*GENERO*
	/LIST;
RUN;

* SALVAR A TABELA EM OUTRA LIB ;
DATA DANIEL.CADASTRO_PRODUTO_V2;
	SET TESTE;
	RENAME LANCAMENTO = FLAG_LANCAMENTO; /* TROCAR NOME DA COLUNA */
	LABEL GENERO = 'GÊNERO'
		LANCAMENTO = 'MARCA *SIM* PARA JOGOS QUE SÃO LANÇAMENTO E *NÃO* CASO CONTRÁRIO';
RUN;

* VER DETALHES DA TABELA CRIADA ;
PROC CONTENTS
	DATA= DANIEL.CADASTRO_PRODUTO_V2;
RUN;

