/*
* ANÁLISE SOBRE A VARIÁVEL DE DATA DA BASE DE CADASTRO PRODUTO
*/

/* 
* SE REPARAR NO FINAL DA TABELA GERADA POR ESSE COMANDO, 
* MOSTRA QUE TEM 3 CAMPOS EM BRANCO
*/

LIBNAME DANIEL "/work/sistema/cib/daniel_sas";

PROC FREQ
	DATA=DANIEL.CADASTRO_PRODUTO_V2;
	TABLE DATA;
RUN;

* CRIAR UMA TABELA APENAS COM AS LINHAS ONDE DATA É VAZIO;
DATA TESTE1;
	SET DANIEL.CADASTRO_PRODUTO_V2;
	WHERE DATA = .;
RUN;

* PASSO 1: CRIA UMA TABELA APENAS COM AS LINHAS DESEJADAS;
DATA TESTE2;
	SET DANIEL.CADASTRO_PRODUTO_V2;
	WHERE NOME IN ("Soccer","Forgotten Echo","Fireshock");
RUN;

* PASSO 2: CRIA UMA TABELA FREQUÊNCIA PARA ANÁLISAR AS DATAS;
PROC FREQ
	DATA=WORK.TESTE2;
	TABLE NOME*DATA
	/LIST MISSING;
RUN;

* PASSO 3: ESSE É O PASSO 1 E 2 JUNTOS;
PROC FREQ
	DATA= DANIEL.CADASTRO_PRODUTO_V2
	(WHERE=(NOME IN ("Soccer","Forgotten Echo","Fireshock")));
	TABLE NOME*DATA
	/LIST MISSING;
RUN;

* PREENCHER OS CAMPOS DATA EM VAZIO;
DATA WORK.TESTE3;
	SET DANIEL.CADASTRO_PRODUTO_V2;
	IF (DATA = . AND NOME = 'Fireshock') 		THEN DATA = 201706; ELSE
	IF (DATA = . AND NOME = 'Forgotten Echo') 	THEN DATA = 201411; ELSE
	IF (DATA = . AND NOME = 'Soccer') 			THEN DATA = 201709;
RUN;

* PREENCHER OS CAMPOS DATA EM VAZIO MELHORADO;
DATA WORK.TESTE4;
	SET DANIEL.CADASTRO_PRODUTO_V2;

	IF DATA = . THEN DO;
		IF NOME = 'Fireshock' 		THEN DATA = 201706; ELSE
		IF NOME = 'Forgotten Echo' 	THEN DATA = 201411; ELSE
		IF NOME = 'Soccer' 			THEN DATA = 201709;
	END;
RUN;

* CHECAR SE AS DATAS ESTÃO PREENCHIDAS;
PROC FREQ
	DATA= WORK.TESTE4
	(WHERE=(NOME IN ("Soccer","Forgotten Echo","Fireshock")));
	TABLE NOME*DATA
	/LIST MISSING;
RUN;


* OUTRA MANEIRA DE PREENCHER AS DATAS EM BRANCO;
DATA WORK.TESTE5;
	SET DANIEL.CADASTRO_PRODUTO_V2;

	IF DATA = . THEN DO;
		SELECT(NOME);
			WHEN ('Fireshock')		DATA = 201706;
			WHEN ('Forgotten Echo')	DATA = 201411;
			WHEN ('Soccer')			DATA = 201709;
			OTHERWISE;
		END;
	END;

RUN;

* CHECAR SE AS DATAS ESTÃO PREENCHIDAS;
PROC FREQ
	DATA= WORK.TESTE5
	(WHERE=(NOME IN ("Soccer","Forgotten Echo","Fireshock")));
	TABLE NOME*DATA
	/LIST MISSING;
RUN;

* CRIAR UMA NOVA TABELA COM A COLUNA FLAG_LANCAMENTO E A LABEL GÊNERO;
DATA DANIEL.CADASTRO_PRODUTO_V3;
	SET TESTE5;

	IF DATA > 201606 
		THEN FLAG_LANCAMENTO = 'SIM';
		ELSE FLAG_LANCAMENTO = 'NAO';

	LABEL GENERO = 'GÊNERO'
	LANCAMENTO = 'MARCA *SIM* PARA JOGOS QUE SÃO LANÇAMENTO E *NÃO* CASO CONTRÁRIO';
RUN;


* COMPARAR O RESULTADO APÓS RESOLVER O PROBLEMA DAS DATAS EM VAZIO;
PROC FREQ
	DATA=DANIEL.CADASTRO_PRODUTO_V2;
	TABLE FLAG_LANCAMENTO
	/LIST;
RUN;
PROC FREQ
	DATA=DANIEL.CADASTRO_PRODUTO_V3;
	TABLE FLAG_LANCAMENTO
	/LIST;
RUN;

